### ISSUE TITLE
Local setup instructions are incorrect?

### ISSUE THREAD

**Issue by trymzet** [dbt-labs/jaffle-shop#3]
It seems the local setup instructions are incomplete/incorrect. Here's what worked for me -- notice I had to manually edit `profiles.yml` and `dbt_project.yml` (since I don't have Snowflake) and install `dbt-duckdb` dependency.

1. Clone the repo
```bash
git clone https://github.com/dbt-labs/jaffle-shop.git && cd jaffle-shop
```

2. Configure `profiles.yml` and `dbt_project.yml`
- remove all profiles except `duckdb` in `profiles.yml`
- change `profile` in `dbt_project.yml` to `duckdb`

3. Set up the rest of the stuff
```bash
python -m venv .venv && \
source .venv/bin/activate && \
pip install -r requirements-core.txt && \
pip install dbt-duckdb && \
dbt deps && \
dbt seed
```

**Comment by gwenwindflower** [comment]
Thank you for this! We've actually updated the repo in recent months to focus on the Cloud CLI, and moved the data warehouse-in-a-box type of setup to live at https://github.com/dbt-labs/jaffle_shop_duckdb to create easier setup flows that are more focused. Appreciate this though!
